yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint shell script
      run: |
        chmod +x ./data/etc/Spotmarket-Switcher/controller.sh
        shellcheck ./data/etc/Spotmarket-Switcher/controller.sh
