name: basic
on:
  push:
  pull_request:
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt-get install yamllint
      - name: Yamllint all YAML files
        run: |
          yamllint .github/workflows/*.yml | \
            grep -v line-length | \
            grep error && failure || echo "No errors found."
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for dockerenv file
        run: |
          (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Show shellcheck version
        run: |
          shellcheck --version
      - name: Lint all shell scripts
        run: |
          # https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md
          # ... (der restliche Teil bleibt unverändert)
  execute:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy sample.config.txt to config.txt
        run: cp scripts/sample.config.txt scripts/config.txt
      - name: Extend default set of UNIX tools
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get install wget curl dbus sed gawk
          else
            echo "I: Nothing to install for ${{ matrix.os }}"
          fi
      - name: Install
        run: ./victron-venus-os-install.sh
        env:
          DEBUG: 1
          DESTDIR: /tmp/testing
      - name: Control
        run: scripts/controller.sh
        env:
          DEBUG: 1
          LOG_FILE: /tmp/testing_controller.log
      - name: Run
        run: scripts/run
        env:
          DEBUG: 1
          rc_local_file: /tmp/testing_rc.local
