name: Main Versioning

# This workflow triggers when a pull request to the 'main' branch is closed
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update_version:
    # Ensure this job only runs if the PR was merged, not just closed without merging
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update VERSION in main
        run: |
          # Remove the -DEV suffix from the version number
          NEW_VERSION=$(sed -n 's/^VERSION=\"\(.*\)-DEV\"$/\1/p' scripts/controller.sh)
          sed -i "s/^VERSION=\".*\"$/VERSION=\"${NEW_VERSION}\"/" scripts/controller.sh
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update version to ${NEW_VERSION}"
          git push origin main
