name: venus
on:
  workflow_dispatch:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: victronenergy/venus-docker
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Install more UNIX tools
        run: |
          ls /etc
          #sudo opkg update
          #sudo opkg install wget
          #sudo opkg install curl
      - name: Execute Installation under Venus OS
        run: |
          echo pwd
          pwd
          echo ls
          ls
          echo victron-venus-install.sh
          if ./victron-venus-os-install.sh ; then
             echo "[OK]"
          else
             echo "[FAIL]"
             pwd
             find . | head -n 30
             exit 1
          fi
        env:
          NO_REBOOT: 1
          DEBUG: 1
      - name: Execute Run-Script under Venus OS
        run: /data/etc/Spotmarket-Switcher/service/run
        env:
          DEBUG: 1
      - name: Execute Control-Script under Venus OS
        run: |
          if [ -x /data/etc/Spotmarket-Switcher/controller.sh ]; then
            echo "W: Seems ok, just not executing controller.sh because of known to be missing curl binary."
          else
            echo "E: controller.sh was not installed."
            exit 1
          fi
        env:
          DEBUG: 1
